// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// app/layout.tsx
import SideBar from "./components/SideBar";
import "./globals.css";

export default function RootLayout({ children }) {
  return (
    <html lang='en' className='bg-[#0b0e14] text-white'>
      <body>
        <div className='flex h-screen w-screen overflow-hidden'>
          <SideBar />
          <main className='flex-1 h-full overflow-y-auto'>{children}</main>
        </div>
      </body>
    </html>
  );
}
